export interface AEngrs {  
    id: number, 
    gradation_sl_no: number, 
    engineer_name: string, 
    caste_alias: string, 
    caste_name: string, 
    year_allot_psc: string, 
    year_passing_de: string, 
    engineer_dob: Date,
    engineer_dor: Date,
    assistant_engineers_doj: Date,
    assistant_engineers_doc: Date,
    ee_higher_scale_date: Date,
    gradation_list_wef: Date,
    service_status: string,
    notes: string,
    year: string,
    created_at: Date,
    updated_at: Date,
    designation_id: number;
}