export interface JEngrs {  
  id: number, 
  gradation_sl_no: number, 
  engineer_name: string, 
  caste_alias: string, 
  caste_name: string, 
  designation_alias: string, 
  engineer_dob: Date,
  engineer_dor: Date,
  junior_engineers_doj: Date,
  junior_engineers_doc: Date,
  year_allot_psc: string,
  year_passing_de: string,   
  gradation_list_wef: Date,
  service_status: string,
  notes: string,
  year: string,
  created_at: Date,
  updated_at: Date,
  designation_id: number
}